In [33]:
import pickle
loaded_model = pickle.load(open("model_pickle.dat", "rb"))

In [34]:
import pandas as pd
df = pd.read_csv('InputFormat.csv')

In [35]:
y_pred_proba = loaded_model.predict_proba(df) #Predicting probability
y_pred = loaded_model.predict(df) #Predicting Frauds

C:\Users\faiza\anaconda3\lib\site-packages\xgboost\data.py:114: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase " +

In [37]:
df1= pd.DataFrame(y_pred_proba, columns = ['Non_Fraud_Probability','Fraud_Probabilty'])
df["Fraud"]= pd.DataFrame(y_pred, columns = ['Fraud'])
df["Fraud_Probabilty"] = df1["Fraud_Probabilty"]
df.head(10)

,policy_state_IL,policy_state_IN,policy_state_OH,policy_csl_100/300,policy_csl_250/500,policy_csl_500/1000,insured_sex_FEMALE,insured_sex_MALE,insured_education_level_Associate,insured_education_level_College,...,number_of_vehicles_involved,bodily_injuries,witnesses,total_claim_amount,injury_claim,property_claim,vehicle_claim,vehicle_age,Fraud,Fraud_Probabilty
0,1,0,0,0,1,0,0,1,1,0,...,1,0,0,2640,440,440,1760,3,0,0.002501
1,1,0,0,1,0,0,1,0,0,0,...,1,2,2,34290,3810,3810,26670,5,0,0.001498
2,0,0,1,1,0,0,0,1,1,0,...,1,2,3,37280,0,0,37280,22,0,0.362099
3,1,0,0,1,0,0,1,0,0,0,...,1,2,0,70500,7050,14100,49350,11,0,0.014685
4,1,0,0,0,0,1,1,0,0,0,...,1,1,1,3190,580,290,2320,14,0,0.016970
5,0,0,1,1,0,0,1,0,1,0,...,3,0,2,42700,0,6100,36600,7,0,0.280230
6,0,1,0,0,1,0,0,1,0,0,...,3,1,3,56160,6240,12480,37440,16,0,0.004670
7,1,0,0,1,0,0,0,1,0,0,...,1,2,1,77330,14060,14060,49210,4,0,0.301195
8,0,0,1,0,0,1,1,0,0,0,...,1,0,0,40700,4070,4070,32560,18,1,0.948867
9,1,0,0,1,0,0,0,1,0,1,...,1,0,0,5600,700,700,4200,11,0,0.211855